name: Build Test and Deploy StudentAPP
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest  
    strategy:
      matrix:
        node-version: [ '16.x', '18.x', '20.x' ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Fix security issues with force
        run: npm audit fix --force
      - name: Check for security issues
        run: npm audit

  test:
    needs: security
    runs-on: ubuntu-latest  
    strategy:
      matrix:
        node-version: [ '16.x', '18.x', '20.x' ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Start the App
        run: npm start &
      - name: Run the tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.TOKEN }}